version: '2'
services:
  web:
    environment:
      - COUPLING_IN_MEMORY=true
      - AUTH0_CLIENT_SECRET
      - CLIENT_PATH
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: coupling-prod
    ports:
      - "3000:3000"