version: '2'
services:
  web:
    hostname: web
    networks:
      - web-net
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: coupling-prod
    ports:
      - "3000:3000"
    links:
      - "dynamo:dynamo"
  dynamo:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - web-net

networks:
  web-net: