FROM node:11-alpine

WORKDIR /usr/src/app

ENV \
  PUBLIC_HOST=web \
  MONGOHQ_URL=mongodb://mongo/Coupling \
  MONGO_CONNECTION=mongodb://mongo \
  NODE_ENV=production

COPY package.json yarn.lock /usr/src/app/

RUN yarn install --production

COPY startup.js /usr/src/app/
COPY build /usr/src/app/build/

CMD ["yarn", "run", "start-built-app"]
EXPOSE 3000 8125
