FROM node:5-slim

WORKDIR /usr/src/app

COPY ["package.json", "/usr/src/app/"]
RUN npm install --production
COPY . /usr/src/app
ENV \
  PUBLIC_HOST=web \
  MONGOHQ_URL=mongodb://mongo/Coupling \
  MONGO_CONNECTION=mongodb://mongo

CMD ["npm", "start"]
EXPOSE 3000
