rootProject.name = "Coupling"

includeBuild("plugins")
includeBuild("coupling-libraries")
include("action")
include("client")
include("e2e")
include("export")
include("import")
include("json")
include("model")
include("repository-core")
include("repository-compound")
include("repository-dynamo")
include("repository-memory")
include("repository-validation")
include("sdk")
include("server")
include("server_action")
include("stub-model")
include("test-action")
include("test-logging")
