version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:9-jdk
      - image: amazon/dynamodb-local
        command: -Xmx1G -jar DynamoDBLocal.jar -inMemory
      - image: selenium/standalone-chrome
    environment:
      SELENIUM_ADDRESS: http://localhost:4444/wd/hub
      JAVA_TOOL_OPTIONS: -XX:MaxRAM=2g
      GRADLE_OPTS: -XX:+HeapDumpOnOutOfMemoryError
      COUPLING_IN_MEMORY: true
    steps:
      - checkout
      - restore_cache:
          key: coupling-cache-39-{{ .Branch }}
      - run: "./gradlew kotlinNodeJsSetup"
      - run: "./gradlew :client:packageJson kotlinNpmInstall"
      - run: "./gradlew packageJson kotlinNpmInstall"
      - run: "./gradlew testPackageJson kotlinNpmInstall"
      - run: "./gradlew jsEndpointTestPackageJson endToEndTestPackageJson kotlinNpmInstall"
      - run: "./gradlew yarn"
      - save_cache:
          key: coupling-cache-39-{{ .Branch }}
          paths:
            - "~/.gradle"
            - ".gradle"
            - "client/.gradle"
            - "node_modules"
            - "/root/.konan"
      - run: "./gradlew build check -x :repository:mongo:check"
      - run:
          name: Copy test results
          command: |
            mkdir -p build/test-output/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} build/test-output/junit/{} \;
          when: always
      - run:
          name: Copy test reports
          command: |
            ./gradlew copyReportsToCircleCIDirectory
          when: always
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
  buildMongo:
    docker:
      - image: circleci/openjdk:9-jdk
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run: "./gradlew :repository:mongo:check --no-parallel -Dorg.gradle.configureondemand=false"
      - run:
          name: Copy test results
          command: |
            mkdir -p build/test-output/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} build/test-output/junit/{} \;
          when: always
      - run:
          name: Copy test reports
          command: |
            ./gradlew copyReportsToCircleCIDirectory
          when: always
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
  deploy-prod:
    docker:
      - image: openjdk:13-jdk
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          key: coupling-cache-39-{{ .Branch }}
      - setup_remote_docker
      - run: "./gradlew buildProductionImage pushProductionImage"
  notify-aws:
    docker:
      - image: mikesir87/aws-cli
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_PAGER: ""
    steps:
      - run: "aws ecs update-service --service Coupling-service --force-new-deployment --no-paginate"
  update-client:
    docker:
      - image: circleci/openjdk:9-jdk
      - image: circleci/mongo:latest
      - image: amazon/dynamodb-local
        command: -Xmx1G -jar DynamoDBLocal.jar -inMemory
      - image: selenium/standalone-chrome
    environment:
      SELENIUM_ADDRESS: http://localhost:4444/wd/hub
      JAVA_TOOL_OPTIONS: -XX:MaxRAM=2g
      GRADLE_OPTS: -XX:+HeapDumpOnOutOfMemoryError
      COUPLING_IN_MEMORY: true
    steps:
      - checkout
      - restore_cache:
          key: coupling-cache-39-{{ .Branch }}
      - run: "./gradlew :client:updateDependencies"
      - run: "./gradlew kotlinNodeJsSetup"
      - run: "./gradlew packageJson testPackageJson kotlinNpmInstall"
      - run: "./gradlew jsEndpointTestPackageJson endToEndTestPackageJson kotlinNpmInstall"
      - run: "./gradlew yarn"
      - run: "./gradlew assemble"
      - run: "./gradlew build check --no-parallel"
      - run:
          name: Copy test results
          command: |
            mkdir -p build/test-output/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} build/test-output/junit/{} \;
          when: always
      - run:
          name: Copy test reports
          command: |
            ./gradlew copyReportsToCircleCIDirectory
          when: always
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
      - run: "git add ."
      - run: "git config user.email \"robert.f.murdock@gmail.com\""
      - run: "git config user.name \"CircleCI in a RoB Suit\""
      - run: "git commit -m 'Automatic client dependency update.' || echo 'Ignoring no changes'"
      - run: "git push"
  update-server:
    docker:
      - image: circleci/openjdk:9-jdk
      - image: circleci/mongo:latest
      - image: amazon/dynamodb-local
        command: -Xmx1G -jar DynamoDBLocal.jar -inMemory
      - image: selenium/standalone-chrome
    environment:
      SELENIUM_ADDRESS: http://localhost:4444/wd/hub
      JAVA_TOOL_OPTIONS: -XX:MaxRAM=2g
      GRADLE_OPTS: -XX:+HeapDumpOnOutOfMemoryError
      COUPLING_IN_MEMORY: true
    steps:
      - checkout
      - restore_cache:
          key: coupling-cache-39-{{ .Branch }}
      - run: "./gradlew :server:updateDependencies"
      - run: "./gradlew kotlinNodeJsSetup"
      - run: "./gradlew packageJson testPackageJson kotlinNpmInstall"
      - run: "./gradlew jsEndpointTestPackageJson endToEndTestPackageJson kotlinNpmInstall"
      - run: "./gradlew yarn"
      - run: "./gradlew assemble"
      - run: "./gradlew build check"
      - run:
          name: Copy test results
          command: |
            mkdir -p build/test-output/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} build/test-output/junit/{} \;
          when: always
      - run:
          name: Copy test reports
          command: |
            ./gradlew copyReportsToCircleCIDirectory
          when: always
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
      - run: "git add ."
      - run: "git config user.email \"robert.f.murdock@gmail.com\""
      - run: "git config user.name \"CircleCI in a RoB Suit\""
      - run: "git commit -m 'Automatic server dependency update.' || echo 'Ignoring no changes'"
      - run: "git push"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - buildMongo
      - deploy-prod:
          requires:
            - build
            - buildMongo
          filters:
            branches:
              only: master
      - notify-aws:
          requires:
            - deploy-prod
  update-client:
    triggers:
      - schedule:
          cron: "0 16 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-client
  update-server:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-server
