version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.2
  coupling-orb:
    orbs:
      browser-tools: circleci/browser-tools@1.1.0
    executors:
      standard:
        machine:
          image: ubuntu-2004:202104-01
        environment:
          COUPLING_IN_MEMORY: "true"
          SKIP_MONGO_TESTS: "true"
          GRADLE_OPTS: -XX:+HeapDumpOnOutOfMemoryError
          _JAVA_OPTIONS: "-Xmx3g"
          AWS_DEFAULT_REGION: us-east-1
    commands:
      setup:
        steps:
          - run: |
              set +e
              curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
              export NVM_DIR="/opt/circleci/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              nvm install node
              nvm alias default node

              echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
              echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
          - browser-tools/install-chrome
          - browser-tools/install-chromedriver
          - run:
              name: Add hostnames
              command: |
                sudo tee -a /etc/hosts \<<<'127.0.0.1 static.localhost socket.localhost'
                cat /etc/hosts
          - restore_cache:
                key: coupling-cache-4-{{ .Branch }}
      collect-results:
        steps:
          - save_cache:
                key: coupling-cache-4-{{ .Branch }}
                paths:
                  - "~/.gradle"
          - run:
              name: Copy test reports
              command: |
                ./gradlew composeLogs collectResults
              when: always
          - store_artifacts:
              path: build/test-output
          - store_test_results:
              path: build/test-output
      commit-push:
        parameters:
          update_type:
            type: string
        steps:
          - run: "git add ."
          - run: "git config user.email \"robert.f.murdock@gmail.com\""
          - run: "git config user.name \"CircleCI in a RoB Suit\""
          - run: "git commit -m 'Automatic <<parameters.update_type>> update.' || echo 'Ignoring no changes'"
          - run: "git push"
jobs:
  build:
    executor: coupling-orb/standard
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - coupling-orb/setup
      - aws-cli/setup
      - run: "./gradlew :sdk:check"
      - run: "./gradlew :sdk:check"
      - run: "./gradlew :sdk:check"
      - run: "./gradlew :sdk:check"
      - run: "./gradlew release build check"
      - coupling-orb/collect-results
  lambda-deploy:
    executor: coupling-orb/standard
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - coupling-orb/setup
      - aws-cli/setup
      - run: "./gradlew serverlessDeploy"
      - coupling-orb/collect-results
  update-client:
    executor: coupling-orb/standard
    steps:
      - checkout
      - run: "./gradlew updateDependencies -PpackageJson=client/package.json"
      - coupling-orb/setup
      - run: "./gradlew build"
      - coupling-orb/collect-results
      - coupling-orb/commit-push:
          update_type: client dependency
  update-server:
    executor: coupling-orb/standard
    steps:
      - checkout
      - run: "./gradlew updateDependencies -PpackageJson=server/package.json"
      - run: "./gradlew updateDependencies -PpackageJson=e2e/package.json"
      - coupling-orb/setup
      - run: "./gradlew build"
      - coupling-orb/collect-results
      - coupling-orb/commit-push:
          update_type: server dependency
  update-gradle-deps:
    executor: coupling-orb/standard
    steps:
      - checkout
      - run: "./gradlew useLatestVersions :plugins:useLatestVersions"
      - coupling-orb/setup
      - run: "./gradlew build"
      - coupling-orb/collect-results
      - coupling-orb/commit-push:
          update_type: gradle dependency
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
  update-client:
    triggers:
      - schedule:
          cron: "0 16 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-client
  update-server:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-server
  update-gradle-deps:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-gradle-deps
