service: coupling-server

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: coupling-server-${opt:stage, 'local'}-notifyConnect
  environment:
    COUPLING_IN_MEMORY: false
    CLIENT_BASENAME: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):CLIENT_BASENAME}
    WEBSOCKET_HOST: ${env:WEBSOCKET_HOST, file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):WEBSOCKET_HOST}
    PUBLIC_URL:	${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):PUBLIC_URL}
    COOKIE_DOMAIN: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):COOKIE_DOMAIN}
    CLIENT_PATH: ${env:CLIENT_PATH}
    AUTH0_CLIENT_ID: ${ssm:/AUTH0_CLIENT_ID~true}
    AUTH0_CLIENT_SECRET: ${ssm:/AUTH0_CLIENT_SECRET~true}
    AZURE_AD_CLIENT_ID: ${ssm:/AZURE_AD_CLIENT_ID~true}
    AZURE_AD_CLIENT_SECRET: ${ssm:/AZURE_AD_CLIENT_SECRET~true}
    STAGE: ${opt:stage, 'local'}
functions:
  api:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverless
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  connectHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketConnect
    events:
      - websocket: $connect
  notifyConnect:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.notifyConnect
  disconnectHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketDisconnect
    events:
      - websocket: $disconnect
  messageHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketMessage
    events:
      - websocket: $default
plugins:
  - serverless-offline-ssm
  - serverless-offline
custom:
  serverless-offline-ssm:
    stages:
      - local
    ssm:
      AUTH0_CLIENT_ID: null
      AUTH0_CLIENT_SECRET: null
      AZURE_AD_CLIENT_ID: null
      AZURE_AD_CLIENT_SECRET: null
  serverless-offline:
    allowCache: true