service: coupling-server

frameworkVersion: '3'

package:
  patterns:
    - '!**'
    - 'build/executable/**'
plugins:
  - serverless-offline
custom:
  serverless-offline:
    allowCache: true
    useInProcess: true
    localEnvironment: true
    host: 0.0.0.0
provider:
  name: aws
  timeout: 20
  stage: ${opt:stage, 'local'}
  runtime: nodejs18.x
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    COUPLING_IN_MEMORY: false
    CLIENT_BASENAME: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):CLIENT_BASENAME}
    WEBSOCKET_HOST: ${env:WEBSOCKET_HOST, file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):WEBSOCKET_HOST}
    PUBLIC_URL:	${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):PUBLIC_URL, env:PUBLIC_URL}
    DYNAMO_PREFIX: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):DYNAMO_PREFIX}
    ENABLE_PRERELEASE_FEATURES: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):ENABLE_PRERELEASE_FEATURES, 'false'}
    CLIENT_URL: ${env:CLIENT_URL, "https://static.localhost"}
    AUTH0_CLIENT_ID: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):AUTH0_CLIENT_ID, ssm:/AUTH0_CLIENT_ID, ''}
    AZURE_AD_CLIENT_ID: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):AZURE_AD_CLIENT_ID, ssm:/AZURE_AD_CLIENT_ID, ''}
    AZURE_AD_CLIENT_SECRET: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):AZURE_AD_CLIENT_SECRET, ssm:/AZURE_AD_CLIENT_SECRET, ''}
    STAGE: ${opt:stage, 'local'}
functions:
  api:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverless
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  connectHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketConnect
    events:
      - websocket: $connect
  notifyConnect:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.notifyConnect
  disconnectHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketDisconnect
    events:
      - websocket: $disconnect
  messageHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketMessage
    events:
      - websocket: $default
