service: coupling-server

frameworkVersion: '3'

package:
  patterns:
    - '!**'
    - '!node_modules/**'
    - 'node_modules/abort-controller/**'
    - 'node_modules/event-target-shim/**'
    - 'node_modules/node-fetch/**'
    - 'build/executable/**'
plugins:
  - serverless-offline
custom:
  serverless-offline:
    allowCache: true
    useInProcess: true
    localEnvironment: true
    noPrependStageInUrl: true
    host: 0.0.0.0
provider:
  name: aws
  timeout: 30
  stage: ${opt:stage, 'local'}
  runtime: nodejs18.x
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    COUPLING_IN_MEMORY: false
    APP_TITLE: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):APP_TITLE}
    CLIENT_BASENAME: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):CLIENT_BASENAME}
    WEBSOCKET_HOST: ${env:WEBSOCKET_HOST, file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):WEBSOCKET_HOST}
    PUBLIC_URL: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):PUBLIC_URL, env:PUBLIC_URL}
    SECRET_SIGNING_SECRET: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):SECRET_SIGNING_SECRET, env:SECRET_SIGNING_SECRET, ssm:/${opt:stage, 'local'}/secret_signing_secret}
    SLACK_CLIENT_ID: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):SLACK_CLIENT_ID, env:SLACK_CLIENT_ID, ssm:/${opt:stage, 'local'}/slack_client_id}
    SLACK_CLIENT_SECRET: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):SLACK_CLIENT_SECRET, env:SLACK_CLIENT_SECRET, ssm:/${opt:stage, 'local'}/slack_client_secret}
    SLACK_SIGNING_SECRET: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):SLACK_SIGNING_SECRET, env:SLACK_SIGNING_SECRET, ssm:/$${opt:stage, 'local'}/slack_signing_secret}
    DISCORD_CLIENT_ID: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):DISCORD_CLIENT_ID, env:DISCORD_CLIENT_ID, ssm:/${opt:stage, 'local'}/discord_client_id}
    DISCORD_CLIENT_SECRET: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):DISCORD_CLIENT_SECRET, env:DISCORD_CLIENT_SECRET, ssm:/${opt:stage, 'local'}/discord_client_secret}
    STRIPE_PUBLISHABLE_KEY: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):STRIPE_PUBLISHABLE_KEY, env:STRIPE_PUBLISHABLE_KEY, ssm:/${opt:stage, 'local'}/stripe_pk}
    STRIPE_SECRET_KEY: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):STRIPE_SECRET_KEY, env:STRIPE_SECRET_KEY, ssm:/${opt:stage, 'local'}/stripe_sk}
    DYNAMO_PREFIX: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):DYNAMO_PREFIX}
    ENABLE_PRERELEASE_FEATURES: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):ENABLE_PRERELEASE_FEATURES, 'false'}
    CLIENT_URL: ${env:CLIENT_URL, "https://static.localhost"}
    CLI_URL: ${env:CLI_URL, "https://cli.localhost"}
    AUTH0_CLIENT_ID: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):AUTH0_CLIENT_ID, ssm:/AUTH0_CLIENT_ID, ''}
    AZURE_AD_CLIENT_ID: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):AZURE_AD_CLIENT_ID, ssm:/AZURE_AD_CLIENT_ID, ''}
    AZURE_AD_CLIENT_SECRET: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):AZURE_AD_CLIENT_SECRET, ssm:/AZURE_AD_CLIENT_SECRET, ''}
    STAGE: ${opt:stage, 'local'}
functions:
  api:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverless
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  connectHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketConnect
    events:
      - websocket: $connect
  notifyConnect:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.notifyConnect
  disconnectHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketDisconnect
    events:
      - websocket: $disconnect
  messageHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketMessage
    events:
      - websocket: $default
