service: coupling-server

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  environment:
    CLIENT_BASENAME: /${opt:stage, 'local'}
    COUPLING_IN_MEMORY: false
    WEBSOCKET_HOST: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):WEBSOCKET_HOST}
    PUBLIC_URL:	${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):PUBLIC_URL}
    COOKIE_DOMAIN: ${file(${env:SERVER_DIR, '.'}/deploy/config.${opt:stage, 'local'}.json):COOKIE_DOMAIN}
    CLIENT_PATH: ${env:CLIENT_PATH}
    AUTH0_CLIENT_ID: ${ssm:/AUTH0_CLIENT_ID}
    AUTH0_CLIENT_SECRET: ${ssm:/AUTH0_CLIENT_SECRET}
    AZURE_AD_CLIENT_ID: ${ssm:/AZURE_AD_CLIENT_ID}
    AZURE_AD_CLIENT_SECRET: ${ssm:/AZURE_AD_CLIENT_SECRET}
functions:
  api:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverless
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  connectHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketConnect
    events:
      - websocket: $connect
  disconnectHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketDisconnect
    events:
      - websocket: $disconnect
  messageHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketMessage
    events:
      - websocket: $default
plugins:
  - serverless-offline-ssm
  - serverless-offline
custom:
  serverless-offline-ssm:
    stages:
      - local
    ssm:
      AUTH0_CLIENT_ID: null
      AUTH0_CLIENT_SECRET: null
      AZURE_AD_CLIENT_ID: null
      AZURE_AD_CLIENT_SECRET: null
  serverless-offline:
    allowCache: true