service: coupling-server

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    CLIENT_BASENAME: /${opt:stage, 'dev'}
    COUPLING_IN_MEMORY: false
functions:
  api:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverless
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  connectHandler:
    handler: ${env:SERVER_DIR, '.'}/build/executable/app.serverlessSocketConnect
    events:
      - websocket: $connect
plugins:
  - serverless-offline
custom:
  serverless-offline:
    allowCache: true