// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/91c08e5b35222508f980db5a97c83bf4b9132aaf/supertest-as-promised/index.d.ts
declare module 'supertest-as-promised' {
// Type definitions for SuperTest as Promised v2.0.2
// Project: https://github.com/WhoopInc/supertest-as-promised
// Definitions by: Tanguy Krotoff <https://github.com/tkrotoff>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

import * as supertest from 'supertest';
import * as superagent from 'superagent';
import { SuperTest, Response } from 'supertest';
import * as PromiseBluebird from 'bluebird';

function supertestAsPromised(app: any): SuperTest<supertestAsPromised.Test>;

namespace supertestAsPromised {
    interface Request extends supertest.Request {
    }

    interface Response extends supertest.Response {
    }

    interface Test extends supertest.Test, superagent.Request {
        toPromise(): PromiseBluebird<Response>;
        timeout(): Promise<Response> & this;
    }

    function agent(app?: any): SuperTest<Test>;

    interface SuperTest<T extends Request> extends supertest.SuperTest<T> {
    }
}
export = supertestAsPromised;
}
