name: Dependency Update
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
permissions: write-all
jobs:
  create-update-branch:
    name: "Create Update Branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          fetch-depth: '25'
      - name: Configure AWS credentials (Local)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::174159267544:role/LocalDevelopment
          aws-region: us-east-1
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '20'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true
      - name: Update Deps
        run: ./gradlew versionCatalogUpdate --no-configuration-cache
      - name: Clean
        run: ./gradlew clean
      - name: Update Yarn Lock
        run: ./gradlew kotlinUpgradeYarnLock --no-configuration-cache --no-build-cache
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "cpr-gradle-update/${{github.job}}/${{github.run_id}}"
          commit-message: "[update-deps] ${{github.workflow}}"
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: autorebase:opt-in
          delete-branch: true
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --rebase --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.COUPLING_PAT }}
