name: Gradle Update
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
jobs:
  create-update-branch:
    name: "Create Update Branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '25'
      - uses: burrunan/gradle-cache-action@v1
        name: Update Deps
        with:
          arguments: useLatestVersions :plugins:useLatestVersions
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: automerge-$GITHUB_ACTION-$GITHUB_RUN_ID
          token: ${{ secrets.COUPLING_PAT }}
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.COUPLING_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
