name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          fetch-depth: '25'
      - name: Configure AWS credentials (Local)
        uses: aws-actions/configure-aws-credentials@v2
        if: ${{ github.ref != 'refs/heads/master' }}
        with:
          role-to-assume: arn:aws:iam::174159267544:role/LocalDevelopment
          aws-region: us-east-1
      - uses: burrunan/gradle-cache-action@v1
        name: Update Deps
        with:
          gradle-version: current
          arguments: wrapper --distribution-type all
      - name: Update Yarn Lock
        run: ./gradlew kotlinUpgradeYarnLock --scan
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "create-pull-request/${{github.job}}/${{github.run_id}}"
          commit-message: "[patch] ${{github.workflow}}"
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.COUPLING_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
